print("Kuukausitulot")
tulot = float(input())
print("Kouluruuan hinta")
kouluru = float(input())
print("Kouluruokailu kerrat kuukaudessa")
kerrat = float(input())
print("Muu eläminen")
eläminen = float  (input())

print("Vuositulot", (tulot*12))
print("Menot kouluruokaan kuukaudessa", (kouluru*kerrat))
print("Menot", (kouluru*kerrat+eläminen))
print("Käteenjää", (tulot-((kouluru*kerrat)+eläminen)))
print("Säästö mahdollisuus 4v", (4*(12*(0.2*(tulot-(eläminen+(kouluru*kerrat)))))))